#!/bin/bash

NAME="ccv"
DIR=/home/nanoafrika/CCV
USER=nanoafrika
GROUP=nanoafrika
WORKERS=2
BIND=unix:/home/nanoafrika/run/ccv.sock
DJANGO_WSGI_MODULE=project.wsgi
LOG_LEVEL=error

cd $DIR
source venv/bin/activate

export PYTHONPATH=$DIR:$PYTHONPATH

exec venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-