# Generated by Django 2.1.2 on 2018-10-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0002_auto_20181011_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message_subject',
            field=models.CharField(max_length=255),
        ),
    ]
