# Generated by Django 2.1.2 on 2018-10-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0003_auto_20181019_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='customer_names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='customer_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message_subject',
            new_name='subject',
        ),
    ]
