# Generated by Django 2.1.2 on 2018-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0006_auto_20181020_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
