# Generated by Django 2.1.2 on 2018-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0007_homeright'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeright',
            options={'verbose_name': 'Home Right Image', 'verbose_name_plural': 'Home Right Images'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='sub_caption',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
