# Generated by Django 2.1.2 on 2018-10-30 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0009_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount to Donate')),
                ('extra', models.TextField(blank=True, verbose_name='Extra Details')),
                ('pledged_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
