# Generated by Django 2.1.2 on 2018-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0011_auto_20181030_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpledge',
            name='when',
            field=models.DateField(blank=True, null=True, verbose_name='When to donate'),
        ),
    ]
