# Generated by Django 2.1.2 on 2018-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0014_auto_20181102_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
