# Generated by Django 2.1.2 on 2018-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0015_team_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
