# Generated by Django 2.1.2 on 2018-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0016_auto_20181102_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='testimonials/')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('testimonial', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
