# Generated by Django 2.1.2 on 2018-11-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0018_aboutus_activities_whatwedo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AddField(
            model_name='activities',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crane.AboutUs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crane.AboutUs'),
            preserve_default=False,
        ),
    ]
