# Generated by Django 2.1.3 on 2018-11-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crane', '0021_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
